version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "edverma"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    groups:
      development-dependencies:
        patterns:
          - "pytest*"
          - "black"
          - "flake8"
          - "mypy"
        update-types:
          - "minor"
          - "patch"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    reviewers:
      - "edverma"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"